### ISSUE TITLE
Error: Failed to load parser '@typescript-eslint/parser'

### ISSUE THREAD

**Issue by ziosa** [kentcdodds/concurrent-react#1]
I run only this command:
`npm run setup --silent`

All output:
```
/bin/sh: yarn: command not found
⚠️  "/Users/szicar01/Repositories/concurrent-react" has a yarn.lock file, but this system does not have the right version of yarn installed. We'll install using npm instead, but you may experience issues. Install the correct version of yarn to get rid of this warning.
📦  starting `npm install --no-package-lock` in "/Users/szicar01/Repositories/concurrent-react"
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
husky > Setting up git hooks
husky > Done
added 1917 packages from 817 contributors and audited 907076 packages in 39.016s
found 0 vulnerabilities

🎉  finished installing dependencies in "/Users/szicar01/Repositories/concurrent-react"
💯  You're all set up! 👏
Error: Failed to load parser '@typescript-eslint/parser' declared in 'package.json » eslint-config-react-app#overrides[0]': Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/szicar01/Repositories/concurrent-react/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/szicar01/Repositories/concurrent-react/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:25)
    at Module._compile (/Users/szicar01/Repositories/concurrent-react/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Determining test suites to run...%
```
Anyway `npm start` works!

**Comment by kentcdodds** [comment]
Hi @ziosa,

Like the warning says, you'll need to install yarn. Or you can use the codesandbox that's linked in the README. Good luck!

**Comment by kentcdodds** [comment]
Here's a link: https://codesandbox.io/s/github/kentcdodds/concurrent-react

**Comment by ziosa** [comment]
I didn't think that this error `Failed to load parser '@typescript-eslint/parser'` depended from _yarn_ . Maybe _**yarn**_ must be a dependecy and not an alternative to _**npm**_.

**Comment by kentcdodds** [comment]
I agree it's probably am issue I should look at eventually. But I don't have the bandwidth to look into that problem right now when there's such a simple solution (the codesandbox)
